HOST: http://infinite-ridge-6275.herokuapp.com/api/v1

--- Zdrojak ---
---
Demo e-shop pro Zdrojak.cz (http://jakubmrozek.github.com/Zdrojak/)
---
--
Stranky
--


Vraceni stranek pro menu layoutu
GET /pages?fields=name,url
< 200
< Content-Type: application/json
[{"name": "O nás", "url": "o-nas"},
{"name": "Obchodní podmínky", "url": "obchodni-podminky"},
{"name": "FAQ", "url": "faq"},
{"name": "Kontakt", "url": "kontakt"}]


Vraceni detailu stranky
GET /pages?url=o-nas
< 200
< Content-Type: application/json
{"name": "O nás",
"text": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit."}




Zobrazení detailu jedné stránky.
GET /pages/{id}
< 200
< Content-Type: application/json
{"id":"5098eaef0496600200000001",
"content":"Lorem ipsum set dolorem",
"title":"Kontakt",
"url":"kontakt"}


Vložení nové stránky do databáze.
POST /pages
> Content-Type: application/json
{"content":"Lorem ipsum set dolorem", "title":"Nákupní řád"}
< 201
< Location: //api/v1/pages/nakupni-rad


Editace jedné stránky v databázi.
PUT /pages/{id}
> Content-Type: application/json
{"content":"Lorem ipsum set dolorem", 
"title":"Nákupní řád e-shopu"}
< 200
< Content-Type: application/json
{"content":"Lorem ipsum set dolorem",
"title":"Nákupní řád e-shopu"}


Smazání stránky z databáze.
DELETE /pages/{id}
< 204


