HOST: http://infinite-ridge-6275.herokuapp.com/api/v1

--- Zdrojak ---
---
Demo e-shop pro Zdrojak.cz (http://jakubmrozek.github.com/Zdrojak/)
---
--
Stranky
--


Vraceni stranek pro menu layoutu
GET /pages?fields={pole}
< 200
< Content-Type: application/json
[{"name": "O nás", "url": "o-nas"},
{"name": "Obchodní podmínky", "url": "obchodni-podminky"},
{"name": "FAQ", "url": "faq"},
{"name": "Kontakt", "url": "kontakt"}]


Vraceni detailu stranky
GET /pages?url={url}
< 200
< Content-Type: application/json
{"name": "O nás",
"text": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit."}


--
Kategorie
--


Seznam všech kategorií
GET /categories
< 200
< Content-Type: application/json
[{"name": "Android", "url": "android"},
{"name": "iPhone", "url": "iphone"},
{"name": "BlackBerry", "url": "blackberry"},
{"name": "Symbian", "url": "symbian"},
{"name": "Windows Phone", "url": "windows-phone"},
{"name": "Levné", "url": "levne"},
{"name": "Příslušenství", "url": "prislusenstvi", "children": [
{"name": "Baterie", "url": "baterie"},
{"name": "Držáky", "url": "drzaky"},
{"name": "Nabíječky", "url": "nabijecky"},
{"name": "Pouzdra", "url": "pouzdra"}
]}]





