HOST: http://infinite-ridge-6275.herokuapp.com/api/v1

--- Zdrojak ---
---
Demo e-shop pro Zdrojak.cz (http://jakubmrozek.github.com/Zdrojak/)
---


--
Stranky
--


Vraceni stranek pro menu layoutu.
GET /pages?fields={pole}
< 200
< Content-Type: application/json
[{"name": "O nás", "url": "o-nas"},
{"name": "Obchodní podmínky", "url": "obchodni-podminky"},
{"name": "FAQ", "url": "faq"},
{"name": "Kontakt", "url": "kontakt"}]


Vraceni detailu stranky.
GET /pages?url={url}
< 200
< Content-Type: application/json
{"name": "O nás",
"text": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit."}


--
Kategorie
--


Seznam všech kategorií.
GET /categories
< 200
< Content-Type: application/json
[{"name": "Android", "url": "android"},
{"name": "iPhone", "url": "iphone"},
{"name": "BlackBerry", "url": "blackberry"},
{"name": "Symbian", "url": "symbian"},
{"name": "Windows Phone", "url": "windows-phone"},
{"name": "Levné", "url": "levne"},
{"name": "Příslušenství", "url": "prislusenstvi", "children": [
{"name": "Baterie", "url": "baterie"},
{"name": "Držáky", "url": "drzaky"},
{"name": "Nabíječky", "url": "nabijecky"},
{"name": "Pouzdra", "url": "pouzdra"}
]}]


Detail kategorie podle URL.
GET /categories?url={url}
< 200
< Content-Type: application/json
{"name": "iPhone", 
"url": "iphone", 
"children": [], 
"minPrice": 1000,
"maxPrice": 23000,
"params": [{
  "name": "Funkce", 
  "code": "funkce", 
  "values": [
    {"code": "wifi", "value": "WiFi"}, 
    {"code": "bluetooth", "value": "BlueTooth"}, 
    {"code": "dual-sim", "value": "Dual SIM"}, 
    {"code": "gps", "value": "GPS"}, 
    {"code": "fm-radio", "value": "FM radio"}
  ]},{
  "name": "Operační paměť", 
  "code": "operacni-pamet", 
  "values": [
    {"code": "256", "value": "256 MB"}, 
    {"code": "512", "value": "512 MB"}, 
    {"code": "1024", "value": "1024 MB"}, 
    {"code": "2048", "value": "2048 MB"}, 
    {"code": "4096", "value": "4096 MB"}
  ]},{
  "name": "Uložiště", 
  "code": "uloziste", 
  "values": [
    {"code": "0-2", "value": "0-2 GB"}, 
    {"code": "2-10", "value": "2-10 GB"}, 
    {"code": "10-50", "value": "10-50 GB"}, 
    {"code": "50-100", "value": "50-100 GB"}, 
    {"code": "100-512", "value": "100-512 GB"}
  ]},{
  "name": "Paměťová karta", 
  "code": "pametova-karta", 
  "values": [
    {"code": "sdhc", "value": "SDHC"}, 
    {"code": "micro-sd", "value": "Micro SD"}, 
    {"code": "micro-sdxc", "value": "Micro SDXC"}, 
    {"code": "sdxc", "value": "SDXC"}, 
    {"code": "micro-sdhc", "value": "Micro SDHC"}
  ]}
]}


--
Objednávky
--


Výběr všech objednávek z databáze.
GET /orders?filter={filter}&limit={limit}&offset={offset}&order={order}&query={query}
< 200
< Content-Type: application/json
{"count":50,
"orders":[
{"number": 123456789,
"date": "2013-01-30T13:27:00Z",
"customer":{"name": "Jakub", "surname": "Mrozek", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
"status": {"code": "pending", "name": "Zpracovává se"},
"products": [
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
],
"transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
"price": 45000},
{"number": 123456789,
"date": "2013-01-30T13:27:00Z",
"customer":{"name": "Jakub", "surname": "Mrozek", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
"status": {"code": "completed", "name": "Dokončeno"},
"products": [
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
],
"transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
"price": 45000},
{"number": 123456789,
"date": "2013-01-30T13:27:00Z",
"customer":{"name": "Jakub", "surname": "Mrozek", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
"status": {"code": "completed", "name": "Dokončeno"},
"products": [
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
],
"transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
"price": 45000},
{"number": 123456789,
"date": "2013-01-30T13:27:00Z",
"customer":{"name": "Jakub", "surname": "Mrozek", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
"status": {"code": "cancelled", "name": "Zrušeno"},
"products": [
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
],
"transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
"price": 45000},
{"number": 123456789,
"date": "2013-01-30T13:27:00Z",
"customer":{"name": "Jakub", "surname": "Mrozek", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
"status": {"code": "completed", "name": "Dokončeno"},
"products": [
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
],
"transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
"price": 45000}
]}


Vložení nové objednávky do databáze.
POST /orders
< 200
< Content-Type: application/json
{"number": "1234567"}


Editace objednavky v databazi.
PUT /orders/{number}
< 204
< Content-Type: application/json


Částečná editace jedné objednávky (např. editace statusu).
POST /orders/{number}
< 204
< Content-Type: application/json


Detail objednávky.
GET /orders/{number}
< 200
< Content-Type: application/json
{"number": 123456789,
"date": "2013-01-30T13:27:00Z",
"customer":{"name": "Jakub", "surname": "Mrozek", "street": "Ostravská 56", "zipcode": "73701", "town": "Český Těšín"},
"status": {"code": "completed", "name": "Dokončeno"},
"products": [
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00701", "name": "Černá barva"}, "price": 15000, "vat": 20, "quantity": 2},
  {"code": "AZ007", "name": "iPhone 4 32GB", "variant": {"code": "AZ00702", "name": "Bílá barva"}, "price": 15000, "vat": 20, "quantity": 1}
],
"transport": {"code": "personal", "name": "Osobní převzetí a platba hotově či kartou", "price": 0},
"price": 45000}



--
Produkty
--


Seznam produktů pro úvodní stránku.
GET /products?homepage=true
< 200
< Content-Type: application/json
[{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
}]


Vyhledávání v produktech.
GET /products?limit={limit}&offset={offset}&query={dotaz}
< 200
< Content-Type: application/json
{"count":120,
"products":[{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
}]}


Detail produktu podle URL.
GET /products?url={url}
< 200
< Content-Type: application/json
{"id":"123456",
"name": "iPhone 4 32GB",
"url": "iphone-4-32gb",
"code": "AZ007",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",     
"text": "<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p><p>Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>",
"photos": [
  {"src":"/img/350x300.gif","width":350,"heigth":300},
  {"src":"/img/350x300.gif","width":350,"heigth":300}
],
"parameters": [
  {"name": "Operační systém", "values": ["iOS"]},
  {"name": "Barva", "values": ["černá", "bílá"]},
  {"name": "Digitální fotoaparát", "values": ["ano"]},
  {"name": "Rozličení fotoaparátu", "values": ["8 Mpx"]},
  {"name": "Pohotovostní doba", "values": ["225 hodin"]},
  {"name": "MP3", "values": ["ano"]},
  {"name": "FM rádio", "values": ["ne"]},
  {"name": "HD video", "values": ["ano"]},
  {"name": "Rozměry", "values": ["115,2 x 58,6 x 9,3 mm"]},
  {"name": "Hmotnost", "values": ["137 g"]}
],
"variants": [
  {"name": "Černá barva"},
  {"name": "Bílá barva"}
],
"producer": "Apple",
"availability": "skladem",
"price": "15000",
"dph": "20"
}


Seznam produktů v kategorii.
GET /products?category={kategorie}&filter={filter}&limit={limit}&offset={offset}&order={order}
< 200
< Content-Type: application/json
{"count":120,
"products":[{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
},
{"name": "iPhone 4 32GB černý",
"url": "iphone-4-32gb-cerny",
"perex": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
"photo": {"src":"/img/350x300.gif","width":350,"heigth":300},
"producer": "Apple",
"availability": "skladem",
"price": 15000
}]}
